JammerCore/JammerCore

src/com/sidebar-calendar/calendar.js
this fixed issue #314
Removed the addition to the months, as it was not being converted correctly. It now displays the calendar 100% correctly - (even with the trophies, that's a neat feature PoV!)
=> Fixed the Calendar Issue #314

scripts/setup.sh
Pointed setup.sh to new database creation script, I don't think the old one was doing anything useful... now the database will be recreated whenever vagrant creates the VM. (I feel like the desired behaviour might be to keep the DB, and have the user manually update it if needed).
=> Updated the setup script's database creation

.gitattributes
Forces "line feed" only line endings on Windows so VM scripts don't crash when they see a "carriage return".
=> Force LF line endings on Windows

src/com/content-common/common-body-markup.less
Currently markdown tables look like this.
This pr changes them to look more like the tables on github
=> Added styling to markdown tables

src/com/content-body/body-edit.js, src/com/content-comments/comments-markup.js, src/com/content-common/common-body-markup.js, src/com/input-textarea/input-textarea.js
Can be used the same way as textarea, except oninput is replaced with onModify.
Fixes #571.
=> InputTextarea component to wrap textarea to centralize errors

src/com/content-common/common.less
word-wrap: break-word doesn't exist anymore, and should be changed to overflow-wrap: break-word (which was already in the CSS and was being overwritten by word-break: break-all). This fixes the odd wrapping behaviour:
=> Remove word-wrap: break-word; on body text

src/com/content-comments/comments.less
An issue regarding big pictures in comments was noticed [by SirRucTheRandom](https://ldjam.com/events/ludum-dare/38/tub-of-war) (see one of the last comments).
A little CSS tweak fixed it:
=> Prevent pictures from overflowing the comment box

src/internal/marked/Renderer.js
#Fixed emojis with underscores in them.
issue raised in #855 .
Any emoji with underscores in them have stopped working. 
Bug was most likely introduced during the markdown parser rewrite (it's so much better btw!!). 
Closes #855
=> Fixed emojis with _ in them

src/com/block-spoiler/spoiler.js, src/com/block-spoiler/spoiler.less, src/com/content-common/common-body-markup.less, src/internal/marked/Lexer.js, src/internal/marked/Parser.js, src/internal/marked/Renderer.js
This implements `!>` block-quote type of spoiler syntax to markdown. Links are also spoiled and content click-through when deactivating spoiler feature in place.
=> Markdown support for spoilers

src/com/input-textarea/input-textarea.js
This prevents the horrible scrolling that happens in long posts/comments. Basically it calculates the expansion of the area and scrolls accordingly but due to the issue of shrinking the area it also disables the window's scroll management while resizing itself. The manual scrolling is nice, because that means you can scroll down a bit so your not writing at the absolute bottom of the screen / still see info about markdown and characters left.
Line 30 & 31 could have been in the if-statement but it's only once that it's not running the if so not really a problem.
Tested on
=> Scroll area

src/internal/marked/Renderer.js
It uses the same `Util.htmldecode` as is used for the normal text-blocks.
=> Fixed issue with inline codespan not decoding

src/com/content-item/item.js
Some small modifications to the results screen. 
Currently untested (haven't opened VM in a month, so it might be fun getting back on track with that)
* Changes
> Graphics: **414** (2.778 average in 29 ratings)
to something more like
> Graphics: **414**th (2.778 average from 29 ratings)
=> [Untested] Modified display of results

public-api/vx/fun.php, public-api/vx/node.php, src/shrub/src/link/link.php, src/shrub/src/link/link_dropbox.php, src/shrub/src/link/link_gamejolt.php, src/shrub/src/link/link_github.php, src/shrub/src/link/link_googledrive.php, src/shrub/src/link/link_itchio.php, src/shrub/src/link/link_newgrounds.php, src/shrub/src/link/link_util.php, src/shrub/src/link/simple_html_dom.php
This is a partial implementation with placeholder API for some `/fun/link` features. I don't understand how I get rid of the error-status when the response is actually constructed as intended.
Also I haven't even started to attempt any database implementations for link-hashes as I'm not sure if you even want me dabbing about them. And I would be more comfortable working on them if I had a full system up an running.
The response from `/link/check` needs of course something on the js-side that reacts to it, when/if we have link-hashing for links out we probably also want a table for link-tags such as the different OS:es and technologies and so on. Then the `/link/check/` should check against these tags before returning the check-results. Now it's just standardized strings like `Linux`.
=> Link checker

sandbox/simulate_ld_event
Early event simulation code in sandbox.
Usage: Navigate to www/sandbox in the dairybox ssh
`./simulate_ld_event 50 actions`
This will churn for a while (~5 minutes), create a bunch of (11) bot accounts on your local instance, and they will post a few dozen posts, many comments and likes, and most will submit games.
Saves detailed logs to /tmp including account user/password pairs and  all request/response data, which is unnecessary but not too much space (few 10s of MBs with the above settings). Current logging should do a good job of surfacing the relevant API request details when there's a failure, but if it fails to, that's where to dig.
There's more work to be done in automating the event through all its stages and having the bots interact with theme selection and voting, but this …
=> Event simulation

sandbox/simulate_ld_event, src/shrub/src/core/db_mysql.php, src/shrub/src/core/json.php
Early useful performance measurement.
* Added further details including detailed query information when ?debug is present
* event simulator consumes this data, and produces a (minimal but useful) HTML report in the current directory when running it.
* This data highlights slow API calls and DB queries individually as well as statistics about all calls in a "tree" based on the http request type and path to the API being used..
* In the report website, click on a node in the tree to display the most expensive API requests or DB queries for that node
=> Perf measurement

public-api/vx/grade.php, sandbox/dev_events.php, sandbox/simulate_ld_event, src/shrub/src/theme/theme_idea.php, src/shrub/tools/grade/grade, src/shrub/tools/theme/theme
Simulation bots vastly improved:
* They read Wikipedia and produce more English-looking gibberish. (Can turn this off with a variable early in the script)
* Simulation code now properly walks through all event states, and bots participate in theme suggestion / slaughter / voting, and vote for games. Theme scripts for scoring the data and generating theme tables, and the grading script are run at the appropriate time, and the correct results are calculated (will follow up on a few things that looked odd though).
* Improvements to readability of the API/DB response time statistics webpage that's generated.
Additionally a few other changes made:
* dev_events.php can now switch the mode of the featured event by rewriting its metadata, so after the simulation runs, you can easily flip around …
=> Test improvement

src/com/tooltip/tooltip-text.js, src/com/tooltip/tooltip.js, src/com/tooltip/tooltip.less
```jsx
<ToolTip PopUpContent={<something />}  />
```
There are a bunch of optional properties to it:
* `ToolTipButtonContent` overrides the default SVG info-icon
* `maxWidth` (default 0.5) sets the maximum width as fraction of the width of the viewport
* `horizontalPadding` (default 6px) number of pixels padding to the edge of the viewport for the popup
* `hideDelay` (default 500ms) a time after mouse exits until toottip is hidden (this helps being able to move mouse from the icon that triggers the tooltip to the popup box. Which is useful if it contains buttons or such).
* `touchNoDoubleClick` (0.1s) a delay for when it isn't possible to hide the tooltip with a click after it has been shown. To counter touch causing flicker show-hide effects.
There's also a subclass for easier use if …
=> Added tootips

public-api/vx/node.php, public-api/vx/note.php, sandbox/simulate_ld_event, src/com/content-comments/comments-comment.js, src/com/content-comments/comments.js, src/shrub/src/note/constants.php, src/shrub/src/note/note.php, src/shrub/src/note/note_complete.php, src/shrub/src/note/note_core.php, src/shrub/src/note/note_flags.php, src/shrub/src/note/note_version.php, src/shrub/src/note/table_create.php, src/shrub/src/notification/notification_core.php
This is the backend work to enable anonymous comments.  
Following are the major changes:
* Add `flags` to note and note version tables. Define two flags (hidden and anonymous)
* Add `allow-anonymous-comments` metadata that can be applied to an 'item' node - The expected value for "enabled" is `1`
* Add `anonymous` optional parameter to `/note/add`, posting anonymously will only succeed if `allow-anonymous-comments` is present and resolves to a nonzero / true value.
* `flags` as well as boolean convenience variables `anonymous` and `hidden` are returned to the client with notes
* Minor site JS changes to not get stuck when anonymous comments are returned, and to render them appropriately.
* Event simulator now marks some games with `allow-anonymous-comments`, and sometimes comments …
=> Anonymous comments

src/com/content-box/box.js, src/com/content-box/box.less, src/com/content-games/games.js, src/com/content-games/games.less, src/com/content-games/grid-selector.js, src/com/content-games/grid-selector.less, src/com/content-item/item-box.js
This introduces a hammer drop-down where number of columns to the games-grid can be selected.
At the moment the `<ContentsGames>` has a default layout of 3 columns for whatever platform in its state.
When there's a parameter for if on mobile, the `defaultLayout` should probably be moved to `props` or `props` should allow for a flag of default view-type to trigger different defaultLayout settings.
The hammer-button that triggers the layout should probably in the near future be placed inside the filter/search bar that most instances will have. That is for a future PR.
The PR also ensures that the number of boxes/cards produces a complete final row with invisible placeholders should need be. This fixes the bug of sometimes getting extra large boxes/cards on the final row.
=> Fixing specific columns and large game

src/shrub/js/tag/tag.js
Idea is to allow UI to query tags based on their names.
Matching is done in case independent and any initial `#` is removed from input.
All tags containing pattern are returned.
Uses existing cache.
Example REPL use:
```
IN:> $Tag.GetContains('y').then(r=>console.log(r.tag.map(t=>t.name)));
OUT:> Array [ "kitty", "Gameboy" ]
```
=> Shrub tags

public-api/vx/node.php, public-api/vx/note.php, sandbox/simulator/model_default, sandbox/simulator/randomtext, src/shrub/src/node/node_core.php, src/shrub/src/notification/constants.php, src/shrub/src/notification/notification_core.php
Now notifications are generated when users are at-mentioned in node / note content.
* `mention` notification is generated if the user was mentioned - and is preferred if there are multiple applicable notification types. If the user would have otherwise received a notification, the user will only receive a `mention`
* list of users mentioned is discovered by regex parsing body in node publish and note add. see `notification_AtTokens` at the end of `notification_core.php`
* List of users is diffed with the previous contents in published node edit and note edit
* In all cases, the list of mentioned users is used to push out notifications.
* Simulator now at-mentions random users to help build data. But this has otherwise been manually tested to work correctly.
* Note: an at-mention does not …
=> Notify on at-mention

src/com/content-comments/comments-comment.js, src/com/content-comments/comments.js
Previous behavior was to give no indication, just not add the comment + clear the comment field.
Tested:
* Can post comments normally
* Enable anonymous comments for node, refresh in another tab, disable anonymous comments, try to post anonymously, confirmed error message appears
* Enable chrome "offline" mode, confirm error message appears on post
* Confirm error message disappears when subsequently posting a comment successfully
=> Improve feedback when comment post fails

src/com/content-notifications/base.js, src/com/content-notifications/notification.js
Things addressed:
* Fix notifications breaks when spam comments are moved to node 0 (tested this case)
* Improve notification merging logic, refactored to be more readable.
* Now: Only merge adjacent notifications, only merge within a 4-hour period, don't merge across read/unread boundary.
* Include RoughAge times in notification text for context
* Comment notifications link to comment anchors `#/comment-[id]` but this doesn't work just yet.
* Lint fixes (not that you can tell in the GitHub diff for `notification.js`)
=> Major revisions to notification logic, fixes bugs and adds improvements.

public-api/vx/notification.php, src/com/content-comments/comments-comment.js, src/com/content-comments/comments.js, src/com/content-comments/comments.less, src/shrub/js/notification/notification.js, src/shrub/src/notification/constants.php, src/shrub/src/notification/notification.php, src/shrub/src/notification/notification_core.php, src/shrub/src/notification/notification_subscribe.php, src/shrub/src/notification/table_create.php
Add arbitrary opt-in and opt-out to notifications. Add a UI button to enable opting in/out, mainly for the users who prefer not to get notifications for every thread.
Changes:
* Add API paths 
* GET `vx/notification/subscription/get/[nodeid]` - Am I subscribed to this node? check `subscribed`
* POST `vx/notification/subscription/add/[nodeid]` - Subscribe me to this thread
* POST `vx/notification/subscription/remove/[nodeid]` - Unsubscribe me from this thread
* If no subscribe/unsubscribe has been registered, the default behavior is your user will receive notificiations if you are the author of the node (or an author for teams), or if you have commented on this thread. Unsubscribe will prevent notifications if either of those are the case, Subscribe will allow notifications without the …
=> Notify optout

src/com/content-comments/comments.js, src/shrub/src/notification/notification_subscribe.php
Apparently I didn't test that the query worked correctly after some changes, Getting subscription status now works correctly.
=> Fix dumb mistakes, now getting subscription status should work correctly

src/shrub/src/notification/notification_core.php
Last update to the notifications system had an error that causes feedback-notification only to occur if you are not the main author of the `node` as reported in #1507 
This makes the proper comparison so that feedbacks are only omitted if you were the one that wrote the note on your own node.
I've run the simulator and logged in as someone who wrote a post and they are now getting feedback notifications.
=> Let main author get feedback notifications again

private/magic.php, public-api/vx/notification.php
This resolves the bug reported in #1533 
For reference there's still the use of the word `note` in:
* `src/shurb/src/comment/constants.php`:
```php
SH_TABLE_NOTE_TREE =                  "note_tree";            // Ancestry
SH_TABLE_NOTE_VERSION =               "note_version";         // History
SH_TABLE_NOTE_LOVE =                  "note_love";
```
* In last sandbox-event I ran (before the change) `sandbox/ld_event.1.stats.html` just make sure you don't use them perhaps?
The use of the word `NOTE` in:
* `src/shrub/src/comment/comment_core.php`, `comment_love.php`, `comment_version.php` pointing to the constants in the `constants.php` above. Also in the `table_create.php`.
=> Fixed missing change to comment

sandbox/simulator/main, sandbox/simulator/model_default
Before the events didn't end up under the `events` node.
Fixed it.
Tested by running simulator and making sure `/events` listed the event.
Seems fine.
=> Made simulator put events under correct node

package.json
You've enabled travis but npm test function fails by default. This should stop travis failing till we add real tests.
#1548
=> Stops travis failing

src/com/dialog/login/login.js
In firefox the name-input wasn't given autofocus for some reason. Now it does.
=> Make name have focus when clicking login

src/com/content-notifications/base.js, src/com/content-notifications/notification.js, src/com/nav-link/link.js, src/com/view/bar/bar-notifications.js, src/com/view/bar/bar.js
This deals with #1556 
It relates to #1413, but opposes it. Though I agree on the general principle of marking things read if they are read. It is a bit problematic given our notification-system.
* Clicking on a notification now has now effect on if it is read or not (since it is a bit obscure in how the marking read works, now marking read only happens if one clicks 'Mark read').
* Nav-change doesn't cause any error and shows pages like they should be.
* Clicking on a notification in the dropdown also hides the dropdown.
* If there are no notifications it will show most recent notifications. This isn't perfect since server doesn't know of user's filters but better than nothing.
=> Notifications issues

src/com/content-common/common-code.less
The code font size seems too small.  The real world example that made me want to do this is on this page
https://ldjam.com/events/ludum-dare/40/pet-overload
Before:
After:
=> Make the code font bigger plz

src/com/page/node/event/games/games.js, src/com/page/root/games/games.js
As per usual ( we should really get round to automating this) the last week is normally in danger mode. Where games that are just shy of being ranked are prioritized.
Currently we have just under 50% of games ranked.
Looking good for getting the same ranked % as the last two events
=> Danger Mode!!

src/com/content-item/item.js
This removes the `Compo` option from items if there's more than one author. It partially deals with #1626 but remains:
=> Limit options for Compo submission

src/com/content-common/common-body-by.less, src/com/content-item/item.js
Was more than enough to put `Super` on top line but now name is kept intact. (Just cropped heavily to make sure it worked).
#1450 Initial issue resolved. Nothing done to space around @ - names because that doesn't seem to relate to how they are used here.
=> Author names no break

src/com/content-comments/comment-autocomplete.js
To make sure you can correctly autocomplete those with a space, autocomplete now uses slugs rather than names for what is inserted into the text.
Tested by making a user with a space and using it.
Resolves #1625
=> Uses slug not name for autocompletes

src/com/content-comments/comments-comment.js
Removes the pen-icon-button when not logged in. 
Related issues:
* Resolves #1649
=> Fixed bug with anon comment being editable by not logged in

src/com/view/bar/bar-notifications.less
Updated less so it will always fit given that the origin of the dropdown isn't moved further from right of the screen.
* Resolves #1645
=> Fixes dropdown so it always fit screen

src/com/content-comments/comments-comment.js, src/com/content-comments/comments.less, src/com/ui/checkbox/checkbox.js
Note that I changed the toggle button for getting notifications on the post to a checkbox because it looked weird with all the mixing of checkboxes and buttons.
Somewhat unrelated, it is a bit strange that the notifications subscription is placed inside the new comments as there's no direct link between subscribing and posting comments. You can subscribe without posting. The action is also performed independently of posting which is contrary to the feeling it gives from its location. Even slightly worse so now that it is a checkbox. What would happen if someone clicks subscribe, and then posts? Does that equal unsubscribe? Or if someone had subscribed before, clicks to unsubscribe and then posts a new comment? This should be its own issue, but since that issue depends on how we handle …
=> Making anon a checkbox in the comment and a tooltip

src/com/content-comments/comments-comment.js, src/com/content-comments/comments-markup.js, src/com/content-comments/comments-markup.less, src/com/content-comments/comments.js
* No disabling of publish/submit comment since that was not popular.
* Adds area blow the input that gives helpful feedback
* Adds "You've reached max comment length" feedback
* Adds "You should not link to own game if commenting on others' games" feedback (Note rule will __not__ activate if (a) commenting on your own game or (b) commenting on a post/non-game).
* Resolves #1636
=> Adding helparea for comments below the comment

src/com/content-timeline/timeline-rategames.js, src/com/content-timeline/timeline-rategames.less, src/com/content-timeline/timeline.js, src/com/page/root/home/home.js
* Adds an item into the root page feed on top, before all other things, that will display 3 games at a time.
* Only visible when there's a featured event on which there is currently voting.
* It randomly selects 3 out of the top 30 on the smart feed. If it wasn't random there would be a big risk of it being useless since many times after a while the top 1-3 games are unplayable to the majority of participants due to requirements or other issues.
* It collapses and expands like other posts in the feed.
* There's a refresh that re-picks the random 3 out of the same 30 games to be shown (without fetching). Re-picking happens up to 7 times. After that it does a new fetch (you see the spinner breifly in the gif) and you have 7 new iterations of 3 random picked games.
* Adds a button/link to …
=> Rate Games in feed

src/com/button-base/base.js, src/com/button-base/base.less, src/com/button-link/link.js, src/com/button-link/link.less, src/com/content-common/common-nav-button.js, src/com/content-common/common-nav-button.less, src/com/content-item/item-rulescheck.js, src/com/content-item/item-rulescheck.less, src/com/content-item/item.js, src/com/content-item/item.less
* Adds a rules check (only pre-submission, never on edits).
* Has to agree with a number of statements before enabling buttons to select game type
* Disabled buttons are grayish and have special cursor, but still react to hover unfortunately.
* Rules data is only stored in the component and not submitted to the server. Therefore if someone answers questions selects type and only saves, they have to answer the same questions again before seeing what they previously selected and being allowed to submit.
* It supports toggling back and forth between edit and preview without loosing answers to questions.
* Updated to warning about too many authors causes compo to be deactivated so it is more prominent since I missed it myself when working on this PR.
* #1646 Bring back checkboxes (this …
=> Rules questions

src/com/content-comments/comments-comment.js, src/com/content-comments/comments.js, src/com/content-comments/comments.less
Resolves #84 
Adds 3 different highlights:
* Node author
* User is author
* Is mention of user
I made the highlight as a border on the left. It's not optimal since meaning is conveyed only by color (not a11y way), and also it makes the content jump in a little.
Above you have normal, normal, mention, self authored (not that self authored trumps node author)
And here we have end of a normal, self, self, self, node author.
If you don't like the border solution and have other ideas for the css, either do a PR to this PR or mock it so I have something to work with. 
I attempted using different background colors but that didn't look very good.
=> Comments highlights

src/com/content-comments/comments-comment.js, src/com/content-comments/comments.js
New behavior:
When viewing a page/post/item you haven't interacted with the checkbox will not be checked indicating that you are currently not subscribing to it.
If you click it, you will subscribe even if you don't post a comment and the checkbox will always reflect your current subscription status.
If you instead write a comment one of two things will happen:
* If you had no subscription status before (had not clicked and not commented) you will automatically subscribe as you comment. The checkbox will reflect this updated
* If you had a subscription status before (had clicked it to any state or commented), that state will remain unchanged.
Resolves #1715
=> Fixing toggle bug for subscribing

src/com/input-dropdown/dropdown.js, src/com/layout/grid/grid-selector.js, src/com/view/bar/bar-notifications.js, src/com/view/bar/bar.js
This makes notifications fetching more aggressively try and limit api-calls by not getting the notifications-feed if there seems to be no new notifications.
It also switches behavior so that it marks all notifications as read when you expand the drop-down (and see/read them). Since there's a notifications feed for you to look at all old notifications, I think this is the best way of limiting the annoying extra clicking that was involved before.
I attempted using the new `ui/dropdown` but that would have needed a substantial refactor of both that component and the notifications-code so instead I stuck with the `input-dropdown/dropdown` and managed to get it work on my computer so that the dropdown collapses when you click anywhere outside the dropdown and when you click on something in it. …
=> Notifications update

public-api/vx/theme.php, src/com/content-event/event-idea.js, src/com/content-event/event-idea.less
This builds upon/includes #1740 
It introduces a live "Please consider if these other themes aren't similar enough to what you are writing that you don't have to suggest it yourself".
It's not perfect but it's a start:
It's hard to capture what may be similar ideas for themes without understanding them so I weighted two common metrics into a single score. It has issues on very short suggestions (2-3 characters long), saying that everything is very similar to everything else short. That might be fine. It will still find if there's an identical or near identical match and present it first.
The other issue is that the `<input onchange/>` function seems a bit buggy or at least sub-optimal. It lags one character in firing the events so if you had previously typed `hell` and just entered an …
=> Theme idea help no dupe

src/internal/time/locale.js
I think you should add global time below calculated local, because I'm sure it does still have a lot of bugs
=> Moscow Standard Time != Mountain Standard Time

scripts/apache/add-ports.sh
provisioning show error
`    default: rm: cannot remove '/etc/apache2/sites-enabled/scotchbox.local.conf': No such file or directory`
because this file no longer exists
```
agrant@dairybox:~$ cd /etc/apache2/sites-enabled/
vagrant@dairybox:/etc/apache2/sites-enabled$ ls
000-default.conf  001-custom-port.conf  010-jammer-work.conf  011-ludumdare-org.conf
```
so I removed attempt to remove it from add-ports.sh
```
rm /etc/apache2/sites-enabled/scotchbox.local.conf
```
=> [WIP] [Scotchbox 3.5] default apache file

scripts/setup.sh
These get run every time Dairy box is provisioned, which could be more than once.
-p on mkdir means it won't attempt to create a dir if it already exists
-sfn is similar and respects symlinks https://unix.stackexchange.com/questions/207294/create-symlink-overwrite-if-one-exists
Also that internal symlink looks wrong to me. Isn't it making `DairyBox/www/public-static/internal/internal` when is should be `DairyBox/www/public-static/internal`
=> [WIP] [Scotchbox 3.5] Don't attempt make dir's if they already exist

src/com/input-textarea/input-textarea.less
Since the textarea background is set to white and the font color is not set, for dark theme users the focused textarea ends up being white on white and unreadable. 
I picked COL_K from this file since it seems to be the opposite of COL_W: https://github.com/ludumdare/ludumdare/blob/master/src/public-ludumdare.com/defs.less , and (presumably?) comes out to black on all sites, but I don't have the stack setup to test this at the moment. If there's a more on brand colour to pick, can update this PR.
=> Fix textarea focus colour on dark themes.

src/main/main.php
Both the server and dev environment produce this warning 
This is fixed by adding `as=fetch; crossorigin`.
`fetch` is used because the svg's are added to the document via javascript fetch request.
I'm not 100% sure why the cross-origin is needed as they're both from ludumdare.org, but it complains if it's not there.
Closes #403 (which was already fixed)
=> fix svg preload warning

public-api/vx/node.php
Looks like #1062 is already addressed and ready to be closed as the text was replaced from "min 3 characters" to "min 3 alphanumeric characters". There's just a tiny typo that this PR fixes.
=> Fix #1062: typo minumum => minimum

Makefile, src/config/eslint.config.json
Rest/spread in object literals was introduced in ECMAScript 2018, so tell ESLint to use that or we'll get `"Parsing error: Unexpected token .."` errors.
`rollup` binary has been moved into a `dist/` directory.
`uglify-js` has updated to version 3 and is now doing `--mangle reserved=["stuff"]` instead of `--mangle -r "stuff"`
=> Fixes to get environment up and running

src/com/content-comments/comments.js, src/com/content-comments/comments.less
Resubmitting because I changed the branch, since I want to work on different issues
Fix #1912 
There is an error if the user has not loaded when the comments render for the first time, this is due to ```getComments``` referencing the user and trying to get the Id of the object that is null at the time
The reason why this was not surfaced in the JS console is because is being caught by the catch for the ```$Comment.GetByNode``` call, but when I try to print it inside the catch this is what I get:
```js
///src/com/content-comments/comments.js:102
.catch(err => {
console.log(err);
this.setState({'error': err});
});
```
My fix is to extract the code that uses the user object to a different function, and execute it only if the user is already loaded, otherwise I added the same call to …
=> Fixed race condition where comments would not load sometimes

src/com/button-clipboard/clipboard.js, src/com/button-clipboard/clipboard.less, src/com/content-common/common-body-title.js, src/com/content-common/common-body-title.less, src/com/content-simple/simple.js, src/com/page/layout.js, src/main/main.php
Closes #1788 
Adds button at the end of post titles. This only shows when on the post's page and not on the main feed.   
When clicked this copies the correct short link to clipboard. If successful the icon is replaced with a  :heavy_check_mark: for two seconds. If it fails the icon changes to :negative_squared_cross_mark: .
Copy to clipboard functionality from https://gist.github.com/lgarron/d1dee380f4ed9d825ca7 we might want to use https://github.com/lgarron/clipboard-polyfill if this simple solution is too buggy but so far it works well.
https://github.com/ludumdare/ludumdare/blob/e7c1dc6b8d155e774d454374898bfb8a7574203c/src/public-url.redirect/main-redirect.php#L15
https://github.com/ludumdare/ludumdare/blob/e7c1dc6b8d155e774d454374898bfb8a7574203c/src/main/main.php#L64
~~I'm not sure …
=> Copy short link button

src/com/view/bar/bar.js
This is a small fix for #109 that doesn't rely on generating favicons:
- stays in sync with the # displayed in the bubble throughout time and user actions.
- displays the original favicon when there are no notifications
- displays 1-9 according to the # of unread notifications
- displays "9+" for more than 9 notifications.
Tested in Chrome, Safari and Firefox:
=> Fix #109: add notification indicator in favicon

.travis.yml
Travis was failing because it was using node 10. This PR updates it to node 16 to match dairybox. 
Also enables some caching of node modules. The svgs rarely change, are small and take a while to process so caching them may be a good idea.
Tavis is not currently running because they moved all the .org stuff to the .com. This means you need to re-auth and re-enable Travis for this repo.
=> Fix travis node error
