public-static/style/theme-hub.css.php, public-theme/theme-slaughter.php, template/core/header.html.php
=> Added a 'tip' informing people they can use arrow keys and space bar

public-api/.htaccess, public-api/vx/user.php, src/com/content-post/post.js, src/com/dialog-activate/activate.js, src/com/dialog-base/base.less, src/com/dialog-login/login.js, src/com/dialog-register/register.js, src/com/sidebar-tv/tv.js, src/com/sidebar-upcoming/upcoming.js, src/external/preact/vdom/index.js, src/public-ludumdare.com/Makefile, src/public-ludumdare.com/main-ld.js, src/shrub/js/config.php, src/shrub/js/user/user.js, src/shrub/src/core/json.php, src/shrub/src/node/constants.php, src/shrub/src/node/node_core.php, src/shrub/src/user/auth.php
Now that the mail server is working, I want to see if php can send emails.
=> Another Pre-Deploy Merge

LICENSE.md
This PR introduces the [MIT license](http://choosealicense.com/licenses/mit/), but IANAL and this isn't my project ¯\\_(ツ)_/¯ 
/cc @povrazor
=> Introduce MIT license

src/com/content-event-slaughter/event-slaughter.js
This commit proposes a fix for issue #330
=> Temporary Fix for Issue #330

README.md
Still basic, but at least it isn't out of date...
=> Make README a little more descriptive

src/com/sidebar-countdown/countdown.less
Removed the bug seen in firefox
Added media query to enable smooth sizing as content gets smaller. Will eventually come back to this to make it smarter :)
=> Bugs away!

src/com/sidebar-countdown/countdown.js
Made the digit rendering a generic function in order to help with the jumbo clock
=> Made some generic functions for countdown

src/com/clock-base/clock.js, src/com/clock-base/clock.less, src/com/clock-base/readme.md, src/com/view-jumboclock/jumboclock.js
=> Mobile and Jumbo Clocks Added

src/com/sidebar-countdown/countdown.js
This should fix #415 but i don't have the vm setup to test it.
Changes the code so that hours wrap from 0 to 23 (rather than 0 to 24).
=> UnTested: Probable fix of #415

src/com/button-love/love.js, src/com/button-love/love.less, src/com/content-post/post.js
=> Created LoveButton component

src/com/dialog-activate/activate.js, src/com/dialog-password/password.js
a fix for #309.
The oninput event only sets a state.
=> Changes the onchange event to oninput

src/com/view-bar/bar.js
Impliments the change suggested in #474.
The icon for the Create Account button has been changed from user to user-add
=> Changes create account icon to user-add from user

src/com/sidebar-tv/tv.less
Proposes a fix for setting the aspect ratio of the screenshot, whilst an image is loading 
Fixes #362
=> Screenshot Aspect Ratio - Fixes #362

src/com/sidebar-tv/tv.less
Reverts ludumdare/ludumdare#538
=> Revert "Screenshot Aspect Ratio - Fixes #362"

src/com/sidebar-tv/tv.js, src/com/sidebar-tv/tv.less
*fingers crossed*
Hahah, okay, so I tried to understand better what you wanted, I closed the last pull request because it was a bit messy :worried:
- Used the SVGIcon
- Only displays on hover over active stream
- Play button loses its hover affect, when hovering over the external button
**Also, I'm so sorry, I don't know what I did, but it displayed so many whitespace changes... I'm so sorry** 
I think maybe its Atom? idk
E.g. :
=> Try #2 at Issue #486

src/com/sidebar-tv/tv.less
=> Fixed image overlap and sizing 

src/com/content-event/event-list.js
Small tweak as described in #632
Changes options from +1(Yes), 0(Maybe), -1(No) to -1(No), 0(Maybe), +1(Yes).
Closes #632
=> Reorder voting options

src/com/nav-spinner/spinner.less
Temp fix for #581. Disables drop shadow on spinner until a better fix is found.
=> Disabled drop shadow on spinner

src/com/nav-spinner/spinner.less
Based off of discussion on #581
Here's the spinner on a few different background colors
Closes #581
=> Readded drop shadow on spinner

src/com/content-common/common-header.less, src/com/content-post/post.js
=> Add guide and info subtype headers

src/com/input-textarea/input-textarea.js
Added a check to make sure the fix only runs on edge since other browsers seem fine.
I tested it worked on my phone, but it might be good for someone else to test on theirs to confirm.
=> Fixed textarea lag bug on mobile

src/custom/marked/marked.js, src/internal/autoembed/autoembed.js
Link handling is bad, some links don't even show up and markdown link titles are ignored.
```md
https://www.zakwest.tech  
[Markdown Test Link](https://www.zakwest.tech)  
[](https://www.zakwest.tech)
https://github.com  
[Markdown Github Test Link](https://github.com)  
[](https://github.com)
https://github.com/ludumdare/ludumdare  
[Markdown Github Test Link](https://github.com/ludumdare/ludumdare)  
[](https://github.com/ludumdare/ludumdare)
https://reddit.com  
[Markdown Reddit Test Link](https://reddit.com)  
[](https://reddit.com)
https://reddit.com/r/ludumdare  
[Markdown Reddit Test Link](https://reddit.com/r/ludumdare)  
[](https://reddit.com/r/ludumdare)
https://youtube.com  
[Markdown Reddit Test Link](https://youtube.com)  
[](https://youtube.com) …
```
=> [WIP] Fix Links

src/custom/marked/marked.js, src/internal/autoembed/autoembed.js
```md
https://www.zakwest.tech  
[Markdown Test Link](https://www.zakwest.tech)  
[](https://www.zakwest.tech)
```
=> Fix [](www.example.com) links

src/custom/marked/marked.js, src/internal/autoembed/autoembed.js
```md
[github](github.com)
```
=> Fixed protocol less links

src/com/content-nav/nav-user.js, src/com/content-user/user-followers.js, src/com/view-content/content.js
Very similar the `/users/<username>/following` but for who's following you `/users/<username>/followers`
=> User Followers 

src/com/dialog-activate/activate.js, src/com/dialog-auth/auth.js, src/com/dialog-common/common.less, src/com/dialog-login/login.js, src/com/dialog-password/password.js, src/com/dialog-register/register.js, src/com/dialog-reset/reset.js, src/com/label-yesno/yesno.js
Tested on screens as small as the iPhone 5 and on my actual 1080p phone. Demo screenshots taken in the iPhone 6 Plus preset on chrome.
Also sets the default yes/no behaviour to show the X instead of nothing.
=> Fixed mobile dialog forms

src/com/content-comments/comments-comment.js, src/com/content-comments/comments.js, src/com/content-comments/comments.less
Compacts and restyles the comments. Moves child comments to actually be a child of the initial comment.
Logged in and viewing your comments:
Logged in and editing your comments (including children)
Logged out or logged in and someone elses comments
=> New comments style

src/custom/marked/marked.js, src/internal/autoembed/autoembed.js, src/public-ludumdare.com/main-ld.js
Anchor links are links that scroll you down the page to an element with an id
e.g. [https://ldjam.com/events/ludum-dare/hosting-guide#/where-should-i-host-my-game](https://ldjam.com/events/ludum-dare/hosting-guide#/where-should-i-host-my-game)
=> Added anchor links

src/com/content-event/event-list.js
=> Wrapped "please log in" text in h4's to differentiate it from themes

src/com/sidebar-calendar/calendar.less
=> Calander, style today even if there is an event on

src/internal/autoembed/autoembed.js, src/internal/autoembed/autoembed.less
=> Wrapper for youtube embeds

src/com/content-user/user-followers.js, src/com/content-user/user-following.js
=> Adds checks to make sure you have followers/following 

src/com/content-games/games.js, src/com/content-timeline/timeline.js, src/com/content-user/user-following.js
Stops "No Games" (and similar) messages flashing up whilst the content is being loaded. Now they only come up if we have tried to load content but got none
=> More No Content Fixes

Makefile
=> Window ?Debug fix, fix, fix (maybe ,fix)

src/com/content-item/item.js
=> [Untested] We don't need that many decimal points

src/com/view-content/content.js, src/internal/headman/headman.js, src/internal/marked/marked.js
In theory should make links from the site look like this on twitter and facebook, but due to the way the site is set up and it's async nature I'm not entirely sure. At the very least it won't break anything, but it needs to be live to really be tested.
=> Open Graph meta initial test

src/com/content-timeline/timeline.js, src/com/header-noob/noob.less, src/com/sidebar-calendar/calendar.js, src/com/sidebar-calendar/calendar.less
Bugs:
* Fixes calendar bugs #500, #546, #847 
* Partial fix for #1026 (code now exists to display Monday-first, but no condition for enabling it is added)
* Fix infinite spinner on empty feed #748 
Side things:
* Add space under noob header (looks better)
* Add trophy icon to LD39 event in calendar (it was set on the wrong day)
=> Calendar fixes & minor other changes

src/com/content-box/box.js
This sorts the medals in the gold - silver - bronze order.
Can't test on local site but have tested that it can build and have tested code assuming that each array item is a string.
=> Sort medals

sandbox/dev_events.php, src/com/content-timeline/timeline.js, src/com/view-content/content.js
Fixed issue #748 again, now tested to work correctly with posts in the system
Suspected fix for all games showing up in the LD-specific games feed (missing parent/superparent method), but I can't easily test. Please confirm.
Added basic  website to automate adding an event in the test server. (sandbox/dev_events.php)
=> Minor fixes

src/com/view-content/content.js
Fixed "balacing" to "balancing"
=> Fix typo in content.js.

src/shrub/src/core/db_query.php
Node magic query was previously fetching all of the magic in the DB, rather than just the magic for nodes it was fetching.
=> DB Query fix (perf improvement)

src/shrub/src/note/note_love.php
(Verified note love still works in test environment data)
=> Fix db typo (perf improvement)

sandbox/dev_tags.php, src/com/content-comments/comments-comment.js, src/compat/ie11/Number/Number.js
* Fix Comment Avatars to only use 64x64 reduced image rather than full image
* Another IE compat fix
* Add dev UI (sandbox/dev_tags.php) to manage platform tags.
=> Comment avatar fix

src/external/preact-devtools/devtools.js, src/main/main.php, src/public-ludumdare.com/main-ld.js
=> Support React Dev Tools when site invoked with ?debug

sandbox/dev_icons.php
=> Add dev site to display icons

src/com/nav-link/link.js
was trying to fix the IE11 SVG issues, but I don't think I'm going to be able to. That seems to be a repeatable but difficult to predict bug in IE11 itself. Found this bug though.
=> Fix IE11 navigation bug (typo)

src/com/content-notifications/notifications.js
May add some more later - I'm debugging the notifications page code which may have some issues with anonymous comments, but I need to finish some other things first.
=> Fixes to notification code

sandbox/simulator/main, sandbox/simulator/randomtext
Reverts ludumdare/ludumdare#1257
=> Revert "Youtube videos occasionally get added to post"

src/com/content-stats/stats-event.js, src/com/content-stats/stats.less, src/com/visualization/piechart/piechart.js, src/com/visualization/piechart/piechart.less, src/com/visualization/piechart/piesegment.js
=> PieCharts & Example Implimentaion

src/com/content-event/event-slaughter.js, src/com/content-event/event-slaughter.less, src/com/visualization/piechart/piechart.js, src/com/visualization/piechart/piechart.less, src/com/visualization/piechart/piesegment.js
=> Adds piechart to theme slaughter page

src/com/content-stats/stats-event.js, src/com/visualization/piechart/piechart.js
I refactored the piechart code to use the correct spelling of labels in #1275, but didn't change it on the event stats page.
=> Fixes for refactoring mistake with piecharts

src/com/content-notifications/base.js, src/com/content-notifications/notification.js, src/com/content-notifications/notifications.js, src/com/view-bar/bar-notifications.js, src/com/view-bar/bar.js
Core fixes to notifications. This might not catch everything but it looks pretty good to me:
* Now working for anonymous comments
* Now loads count immediately instead of 5 minutes after loading the page.
* Fixed some rendering issues
* Fixed spelling & reworded a few things
* Added mark read option to dropdown
* Dismiss dropdown when opening the notification feed
* Don't fetch notification count when browser tab is not focused.
* Fix some bugs in how notification feed page was loading notifications.
Future:
* No change to the styling, notification feed page could probably use some style tweaks
* Need to rework how notifications are merged.
=> Notification fixes

src/internal/marked/Renderer.js
Fixes issues as discussed in the gitter chat.
=> Fixes Link behavior

src/com/content-notifications/base.js, src/com/content-stats/stats-event.js, src/com/view-bar/bar.js
error occurs with when you have an @mention in post notification and also notified comments from that post, 
I didn't run into it on the simulator but it happened to me on the live site
=> Fix rendering error 

src/com/router/router.js
Changes div to have `id="context"` to fix sidebar being in the center of the page for a second during load
=> Router tweak

.eslintignore, .stylelintignore, src/com/fonts.less
Adds `.eslingignore` and `.stylelintignore` files to stop unwantd liniting. 
Closes #1342
=> Stop linting files in src/external

src/com/header/noob/noob.js
Since someone pointed it out to me, i might as well fix it
=> Total nitpick

src/com/content-stats/stats-event.js, src/com/visualization/barchart/barchart.js, src/com/visualization/piechart/piechart.js
* Now able to specifiy weather you want percentages or not (defaults to none)
* Makes all charts on the stats page have percentages on
=> Make percentages configuable on charts

src/com/content-notifications/notification.js
Trying to get the mention correctly output.
Trying to get the UI ready for notifications it doesn't know how to handle.
I have only tested in the sense that it didn't apparently break anything but I don't know how this really will work with unknown notifications. And I didn't have a notification of the right type that caused the previous classification error.
So a bit of warning... but probably not a real problem
=> Attempting fix for mis-represented notifation :grin: and also unknown

src/com/content-simple/simple.js, src/com/dialog/errorpublish/errorpublish.js, src/public-ludumdare.com/main-ld.js
* When name is too short
* When name is reserved
* others
=> Adds a popup when publishing fails

public-api/vx/asset.php, src/com/dialog/errorupload/errorupload.js, src/com/input-textarea/input-textarea.js, src/public-ludumdare.com/main-ld.js
* Fixes impossible condition in php code for upload errors
* Adds pop up when an upload fails
Closes #1090
=> Adds error pop up when an image upload fails

src/com/content-notifications/base.js, src/com/content-notifications/notification.js, src/com/content-notifications/notifications.js, src/com/content-notifications/notifications.less, src/shrub/js/notification/notification.js
This was mostly intended to clean up the code of `notification.js` because it was really hard to work with and maintain.
Also fixed bugs: 
* not tracking friends and friends.
* correctly formatting how friends and people you follow are displayed (this was not rendering their names like it should have).
* fixed bug that would have anonymous feedback crash the notification-code.
Attempted to try and make old feedback-notifications that where typed as comments to still show and filter as feedback. However I would have to manually edit the database for some feedback notifications and make them classified as type `note`. But I don't have the skills for that. It seems at least not to break anything so merge should be safe even if we won't know if this fixed the thing or not until after.
=> Notification cleaning and more

src/com/content-nav/nav-user.js
Quick fix until #1474 is resolved properly.
=> Always show games

src/com/page/event/games/games.js, src/com/page/home/games/games.js
Makes the default filter dange
=> Danger Mode

src/com/page/event/games/games.js, src/com/page/home/games/games.js
To address this concern, https://ldjam.com/events/ludum-dare/40/defense-2150-bc/a-problem-and-a-call-to-action
Changes the default to filter back to smart. I suggest pushing this 12 hours before the deadline.
=> Back to smart filter for the last few hours

src/com/page/event/games/games.js
Not sure why this was jam, it seems strange to have that as the default.
=> Change default filter to All (jam+compo) from Jam

src/com/dialog/login/login.js
https://github.com/ludumdare/ludumdare/issues/1501
The diff is a little messed up, but all I did was put the inputs into a form. I'm pretty sure this is mandatory for safari and firefox to recognize the fields.
=> Remember password

.travis.yml
This Travis job performs the very basic test of building the PR natively on a Linux machine. Just running `make`. There are no databases and such set up yet though.
=> Travis integration, running make

.travis.yml
=> Travis should not use apt, but apt-get

src/com/page/event/mygrades/mygrades-grade-graphs.js, src/com/page/event/mygrades/mygrades.less, src/com/visualization/barchart/bar-axis-tick.js, src/com/visualization/barchart/bar-x-axis.js, src/com/visualization/barchart/bar-y-axis.js, src/com/visualization/barchart/bar.js, src/com/visualization/barchart/barchart.js, src/com/visualization/barchart/barchart.less
Adds optional y and x axis to bar graphs. Y axis can have ticks (both major and minor).
=> Graph axis

src/com/content-event/event-slaughter.js, src/com/content-event/event-slaughter.less, src/com/visualization/piechart/piechart.js
* Unified style with rest of site.
* Hotkeys for yes and no (not flag because people shouldn't abuse it) #1381, #343 ? 
* Colors on buttons, recent vote history and chart match.
* You can change your mind for a vote by clicking on it. #1059, #325 
* CSS animations to show what is updating and happening.
* Code cleaning
* Pie-chart supporting custom color definitions.
I haven't seen #332 so maybe close that one too.
=> Theme slaughter update

src/com/header/whatsup/whatsup.js
=> Fixed '/theme' in whatsup, now using UI code

public-api/vx/node.php, public-api/vx/user.php
=> fixes 'too short' message

src/com/content-item/item.js, src/internal/lib/node.js
=> switched to global node author counter

src/com/content-item/item.js
=> Using checkboxes for item edit

src/com/content-item/item-teambuilding.js, src/com/content-item/item-teambuilding.less, src/com/content-item/item.js, src/com/content-simple/simple.js, src/com/content-user/user-bar.js, src/com/ui/dropdown/dropdown.js, src/shrub/js/node/node.js
* Select what friends you want to add and remove from a simple drop-down.
* Removes old slightly buggy way of adding friends to game.
* Works directly and live and integrates with the preview of the item.
* Only affects items, not posts.
Right now all authors get access to the team-building feature. But it's a question of who should have this right. For now you can remove yourself if you are not main author and you can remove everyone but yourself if you are main author. Everyone gets to add from their own friends (does the api even allow that? Should it allow that?)
* Resolves #1448 
* #1422 may be fixed by this or are there other limitations?
=> Game team building

src/com/autoembed/locallink.js, src/internal/marked/Renderer.js, src/public-ludumdare.com/main-ld.js
Resolves #1339 and possibly some of the other local links issues if they are still open?
=> fixed local links

src/com/content-box/box.js
User = one author
Users = not one author
Resolves #1480
=> Showing icons on jam in games feed

public-api/vx/theme.php
Ooops, I took a peak at the PHP code and this might have been easy. I think this gives a logged in user the right to request all suggested themes this far during the theme-suggestion phase.
Resolves #1709
=> Allow getting suggested themes in suggestion phase.

src/com/content-comments/comments-comment.js
=> Go back to comment edit mode on publish

src/com/content-event/event-slaughter.js
It's not the most beautiful fix, basically checking if `$Node.GetMy` is allowed once per minute. And if not say logged out. Also if a vote gets 401 it sets logged out. And when setting logged out it removes the event listener.
Resolves #1700 #1699 #1592
=> Unbinds hotkeys when logout detected

src/com/dialog/register/register.js, src/com/dialog/reset/reset.js
=> Change email fields to type="email"

src/com/content-event/event-idea.js, src/com/content-event/event-idea.less
Reverts ludumdare/ludumdare#1741
These changes appear to be broken.
=> Revert "Theme idea help no dupe"

src/com/autoembed/youtube.js, src/com/content-comments/comments-comment.js, src/com/content-common/common-body-avatar.js, src/com/content-nav/nav-event.js, src/com/content-nav/nav-item.js, src/com/content-nav/nav-root.js, src/com/content-nav/nav-theme.js, src/com/content-nav/nav-user.js, src/com/page/nav/content.js, src/com/page/nav/event-my.js, src/com/page/nav/event.js, src/com/page/nav/root.js, src/com/ui/button/button-link.js, src/com/view/bar/bar-user.js, src/com/view/bar/bar.js, src/main/main.php
Some work on improving the accessibility of the site, guided by google's lighthouse report.A start on  #1762 but I'm not familiar with the aria stuff.
before
after
- Added title's to all ContentNavButtons
- Added alt's to user avatars
- Added rel=noopenner to youtube embed's open external link
=> Lighthouse fixes

Makefile, public-api/vx/grade.php, public-api/vx/node.php, public-api/vx/node2.php, src/com/content-event/event.js, src/com/content-item/item.js, src/com/content-timeline/timeline.js, src/com/content-user/user-bar.js, src/com/page/root/home/home.js, src/com/sidebar/tv/tv.js, src/com/view/bar/bar.js, src/external/jammertv/jammertv.js, src/public-ludumdare.com/main-ld.js, src/shrub/js/node/node.js, src/shrub/src/node/constants.php, src/shrub/src/node/node_complete.php
By request, here is the current working version of the latest batching improvements.
**This code is unfinished**. It breaks compatibility with the old `featured` data (i.e. `what_node`, `what`, etc).
=> Batching of User and Featured Event data (WIP)

src/com/dialog/login/login.js
As #1750 but without the extra files...
=> Just the login fix

src/com/content-event/event-idea.js
Closes #1904 
sort was used incorrectly. You need to compare to items in the sort function.
I have tested the line in isolation but I haven't set up the dev environment to test it properly.
=> Corrected Sort on theme idea page. #1904

public-api/vx/homework.php, public-api/vx/node.php, public-api/vx/theme.php, sandbox/com/view-content/content.js, sandbox/dev_events.php, sandbox/public-api/vx/feature.php, sandbox/simulator/model_default, src/com/content-event/event-home.js, src/com/content-event/event-theme.js, src/com/content-nav/nav-theme.js, src/com/content-stats/stats-event.js, src/com/header/whatsup/whatsup.js, src/com/page/nav/event.js, src/com/page/node/event/event.js, src/com/page/node/event/games/games.js, src/com/page/root/games/games.js, src/shrub/src/node/table_create.php, src/shrub/tools/event/add-event
=> theme-mode is now event-mode

src/com/content-event/event-list.js
fixes https://github.com/JammerCore/JammerCore/issues/1391
=> Use correct page index for voting round check

src/com/content-item/item.js
=> Improve wording on format selection
